//
// Generated file, do not edit! Created by nedtool 4.6 from src/node/communication/routing/wu2019/wu2019Packet.msg.
//

#ifndef _WU2019PACKET_M_H_
#define _WU2019PACKET_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "RoutingPacket_m.h"
#include "GeoMathHelper.h"
typedef std::vector<int> IntVector;
// }}

/**
 * Enum generated from <tt>src/node/communication/routing/wu2019/wu2019Packet.msg:30</tt> by nedtool.
 * <pre>
 * enum wu2019Packet_Type
 * {
 * 
 *     GP_ROUTING_CONTROL_PACKET = 1;
 *     GP_ROUTING_DATA_PACKET = 2;
 *     GP_ROUTING_JOIN_PACKET = 3;
 *     GP_ROUTING_ADV_PACKET = 4;
 * }
 * </pre>
 */
enum wu2019Packet_Type {
    GP_ROUTING_CONTROL_PACKET = 1,
    GP_ROUTING_DATA_PACKET = 2,
    GP_ROUTING_JOIN_PACKET = 3,
    GP_ROUTING_ADV_PACKET = 4
};

/**
 * Class generated from <tt>src/node/communication/routing/wu2019/wu2019Packet.msg:38</tt> by nedtool.
 * <pre>
 * packet wu2019Packet extends RoutingPacket
 * {
 *     int wu2019PacketKind @enum(wu2019Packet_Type);
 *     int sourceId;
 *     int schedule[];
 *     double remainingEnergy;
 *     IntVector isCH;
 *     IntVector nextCH;
 *     IntVector trace;
 * }
 * </pre>
 */
class wu2019Packet : public ::RoutingPacket
{
  protected:
    int wu2019PacketKind_var;
    int sourceId_var;
    int *schedule_var; // array ptr
    unsigned int schedule_arraysize;
    double remainingEnergy_var;
    IntVector isCH_var;
    IntVector nextCH_var;
    IntVector trace_var;

  private:
    void copy(const wu2019Packet& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const wu2019Packet&);

  public:
    wu2019Packet(const char *name=NULL, int kind=0);
    wu2019Packet(const wu2019Packet& other);
    virtual ~wu2019Packet();
    wu2019Packet& operator=(const wu2019Packet& other);
    virtual wu2019Packet *dup() const {return new wu2019Packet(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getWu2019PacketKind() const;
    virtual void setWu2019PacketKind(int wu2019PacketKind);
    virtual int getSourceId() const;
    virtual void setSourceId(int sourceId);
    virtual void setScheduleArraySize(unsigned int size);
    virtual unsigned int getScheduleArraySize() const;
    virtual int getSchedule(unsigned int k) const;
    virtual void setSchedule(unsigned int k, int schedule);
    virtual double getRemainingEnergy() const;
    virtual void setRemainingEnergy(double remainingEnergy);
    virtual IntVector& getIsCH();
    virtual const IntVector& getIsCH() const {return const_cast<wu2019Packet*>(this)->getIsCH();}
    virtual void setIsCH(const IntVector& isCH);
    virtual IntVector& getNextCH();
    virtual const IntVector& getNextCH() const {return const_cast<wu2019Packet*>(this)->getNextCH();}
    virtual void setNextCH(const IntVector& nextCH);
    virtual IntVector& getTrace();
    virtual const IntVector& getTrace() const {return const_cast<wu2019Packet*>(this)->getTrace();}
    virtual void setTrace(const IntVector& trace);
};

inline void doPacking(cCommBuffer *b, wu2019Packet& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, wu2019Packet& obj) {obj.parsimUnpack(b);}


#endif // ifndef _WU2019PACKET_M_H_

