//
// Generated file, do not edit! Created by nedtool 4.6 from src/node/communication/routing/gpRouting/GPRoutingPacket.msg.
//

#ifndef _GPROUTINGPACKET_M_H_
#define _GPROUTINGPACKET_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "RoutingPacket_m.h"
#include "GeoMathHelper.h"
typedef std::vector<int> IntVector;
// }}

/**
 * Enum generated from <tt>src/node/communication/routing/gpRouting/GPRoutingPacket.msg:30</tt> by nedtool.
 * <pre>
 * enum GPRoutingPacket_Type
 * {
 * 
 *     GP_ROUTING_CONTROL_PACKET = 1;
 *     GP_ROUTING_DATA_PACKET = 2;
 *     GP_ROUTING_JOIN_PACKET = 3;
 *     GP_ROUTING_ADV_PACKET = 4;
 * }
 * </pre>
 */
enum GPRoutingPacket_Type {
    GP_ROUTING_CONTROL_PACKET = 1,
    GP_ROUTING_DATA_PACKET = 2,
    GP_ROUTING_JOIN_PACKET = 3,
    GP_ROUTING_ADV_PACKET = 4
};

/**
 * Class generated from <tt>src/node/communication/routing/gpRouting/GPRoutingPacket.msg:38</tt> by nedtool.
 * <pre>
 * packet GPRoutingPacket extends RoutingPacket
 * {
 *     int GPRoutingPacketKind @enum(GPRoutingPacket_Type);
 *     int sourceId;
 *     int schedule[];
 *     double remainingEnergy;
 *     IntVector isCH;
 *     IntVector nextCH;
 *     IntVector trace;
 * }
 * </pre>
 */
class GPRoutingPacket : public ::RoutingPacket
{
  protected:
    int GPRoutingPacketKind_var;
    int sourceId_var;
    int *schedule_var; // array ptr
    unsigned int schedule_arraysize;
    double remainingEnergy_var;
    IntVector isCH_var;
    IntVector nextCH_var;
    IntVector trace_var;

  private:
    void copy(const GPRoutingPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const GPRoutingPacket&);

  public:
    GPRoutingPacket(const char *name=NULL, int kind=0);
    GPRoutingPacket(const GPRoutingPacket& other);
    virtual ~GPRoutingPacket();
    GPRoutingPacket& operator=(const GPRoutingPacket& other);
    virtual GPRoutingPacket *dup() const {return new GPRoutingPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getGPRoutingPacketKind() const;
    virtual void setGPRoutingPacketKind(int GPRoutingPacketKind);
    virtual int getSourceId() const;
    virtual void setSourceId(int sourceId);
    virtual void setScheduleArraySize(unsigned int size);
    virtual unsigned int getScheduleArraySize() const;
    virtual int getSchedule(unsigned int k) const;
    virtual void setSchedule(unsigned int k, int schedule);
    virtual double getRemainingEnergy() const;
    virtual void setRemainingEnergy(double remainingEnergy);
    virtual IntVector& getIsCH();
    virtual const IntVector& getIsCH() const {return const_cast<GPRoutingPacket*>(this)->getIsCH();}
    virtual void setIsCH(const IntVector& isCH);
    virtual IntVector& getNextCH();
    virtual const IntVector& getNextCH() const {return const_cast<GPRoutingPacket*>(this)->getNextCH();}
    virtual void setNextCH(const IntVector& nextCH);
    virtual IntVector& getTrace();
    virtual const IntVector& getTrace() const {return const_cast<GPRoutingPacket*>(this)->getTrace();}
    virtual void setTrace(const IntVector& trace);
};

inline void doPacking(cCommBuffer *b, GPRoutingPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, GPRoutingPacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef _GPROUTINGPACKET_M_H_

