//
// Generated file, do not edit! Created by nedtool 4.6 from src/node/communication/routing/gambac/GAMBACPacket.msg.
//

#ifndef _GAMBACPACKET_M_H_
#define _GAMBACPACKET_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "RoutingPacket_m.h"
#include "GeoMathHelper.h"
typedef std::vector<int> IntVector;
// }}

/**
 * Enum generated from <tt>src/node/communication/routing/gambac/GAMBACPacket.msg:30</tt> by nedtool.
 * <pre>
 * enum GAMBACPacket_Type
 * {
 * 
 *     GAMBAC_ROUTING_CONTROL_PACKET = 1;
 *     GAMBAC_ROUTING_DATA_PACKET = 2;
 *     GAMBAC_ROUTING_JOIN_PACKET = 3;
 *     GAMBAC_ROUTING_ADV_PACKET = 4;
 * }
 * </pre>
 */
enum GAMBACPacket_Type {
    GAMBAC_ROUTING_CONTROL_PACKET = 1,
    GAMBAC_ROUTING_DATA_PACKET = 2,
    GAMBAC_ROUTING_JOIN_PACKET = 3,
    GAMBAC_ROUTING_ADV_PACKET = 4
};

/**
 * Class generated from <tt>src/node/communication/routing/gambac/GAMBACPacket.msg:38</tt> by nedtool.
 * <pre>
 * packet GAMBACPacket extends RoutingPacket
 * {
 *     int GAMBACPacketKind @enum(GAMBACPacket_Type);
 *     int schedule[];
 *     double remainingEnergy;
 *     IntVector isCH;
 *     IntVector nextCH;
 *     IntVector trace;
 * }
 * </pre>
 */
class GAMBACPacket : public ::RoutingPacket
{
  protected:
    int GAMBACPacketKind_var;
    int *schedule_var; // array ptr
    unsigned int schedule_arraysize;
    double remainingEnergy_var;
    IntVector isCH_var;
    IntVector nextCH_var;
    IntVector trace_var;

  private:
    void copy(const GAMBACPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const GAMBACPacket&);

  public:
    GAMBACPacket(const char *name=NULL, int kind=0);
    GAMBACPacket(const GAMBACPacket& other);
    virtual ~GAMBACPacket();
    GAMBACPacket& operator=(const GAMBACPacket& other);
    virtual GAMBACPacket *dup() const {return new GAMBACPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getGAMBACPacketKind() const;
    virtual void setGAMBACPacketKind(int GAMBACPacketKind);
    virtual void setScheduleArraySize(unsigned int size);
    virtual unsigned int getScheduleArraySize() const;
    virtual int getSchedule(unsigned int k) const;
    virtual void setSchedule(unsigned int k, int schedule);
    virtual double getRemainingEnergy() const;
    virtual void setRemainingEnergy(double remainingEnergy);
    virtual IntVector& getIsCH();
    virtual const IntVector& getIsCH() const {return const_cast<GAMBACPacket*>(this)->getIsCH();}
    virtual void setIsCH(const IntVector& isCH);
    virtual IntVector& getNextCH();
    virtual const IntVector& getNextCH() const {return const_cast<GAMBACPacket*>(this)->getNextCH();}
    virtual void setNextCH(const IntVector& nextCH);
    virtual IntVector& getTrace();
    virtual const IntVector& getTrace() const {return const_cast<GAMBACPacket*>(this)->getTrace();}
    virtual void setTrace(const IntVector& trace);
};

inline void doPacking(cCommBuffer *b, GAMBACPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, GAMBACPacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef _GAMBACPACKET_M_H_

